'use client'

import Link from 'next/link'

export default function TermsPage() {
  const colors = {
    bg: '#14171a',
    text: '#e8e3e3',
    muted: '#6e6a86',
    cyan: '#7eb8da',
  }

  return (
    <div style={{
      minHeight: '100vh',
      background: colors.bg,
      fontFamily: "'JetBrains Mono', 'Fira Code', Consolas, monospace",
      color: colors.text,
    }}>
      {/* Header */}
      <header style={{ borderBottom: `1px solid ${colors.muted}` }}>
        <div style={{
          maxWidth: '800px',
          margin: '0 auto',
          padding: '16px 24px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}>
          <Link href="/" style={{ color: colors.cyan, fontSize: '18px', textDecoration: 'none' }}>
            RegexGPT
          </Link>
          <nav style={{ display: 'flex', gap: '16px' }}>
            <Link href="/" style={{ color: colors.muted, textDecoration: 'none' }}>[Home]</Link>
            <Link href="/privacy" style={{ color: colors.muted, textDecoration: 'none' }}>[Privacy]</Link>
          </nav>
        </div>
      </header>

      {/* Content */}
      <main style={{ maxWidth: '800px', margin: '0 auto', padding: '48px 24px' }}>
        <h1 style={{ color: colors.cyan, marginTop: 0, marginBottom: '8px' }}>Terms of Service</h1>
        <p style={{ color: colors.muted, marginBottom: '32px', fontSize: '14px' }}>
          Last updated: January 2026
        </p>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>1. Acceptance of Terms</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            By accessing or using RegexGPT (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
            If you do not agree to these terms, please do not use the Service. RegexGPT is operated by
            VERIDIAN TOOLS (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;).
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>2. Description of Service</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            RegexGPT is an AI-powered tool that generates regular expressions from natural language
            descriptions and explains existing regex patterns. The Service is provided &quot;as is&quot; and we
            make no guarantees about the accuracy or suitability of generated patterns for any specific use case.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>3. User Accounts</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            To use the Service, you must create an account using a valid email address or third-party
            authentication provider. You are responsible for maintaining the security of your account
            and for all activities that occur under your account.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>4. Subscription and Payments</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            RegexGPT offers free and paid subscription tiers. Paid subscriptions are billed monthly
            through Stripe. You may cancel your subscription at any time through the billing portal.
            Upon cancellation, you will retain access to Pro features until the end of your current
            billing period.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>5. Acceptable Use</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            You agree not to use the Service to:
          </p>
          <ul style={{ lineHeight: '1.7', color: colors.text, paddingLeft: '24px' }}>
            <li>Generate content that is illegal, harmful, or violates the rights of others</li>
            <li>Attempt to circumvent rate limits or access controls</li>
            <li>Reverse engineer or attempt to extract the underlying AI models</li>
            <li>Resell or redistribute the Service without authorization</li>
            <li>Interfere with the operation of the Service</li>
          </ul>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>6. Intellectual Property</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            Regex patterns generated by the Service are provided for your use without restriction.
            You may use generated patterns in any project, including commercial applications.
            The Service itself, including its design, code, and branding, remains the property of VERIDIAN TOOLS.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>7. Disclaimer of Warranties</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.
            WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT GENERATED
            PATTERNS WILL BE SUITABLE FOR YOUR SPECIFIC USE CASE. ALWAYS TEST PATTERNS BEFORE USE IN PRODUCTION.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>8. Limitation of Liability</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, VERIDIAN TOOLS SHALL NOT BE LIABLE FOR ANY INDIRECT,
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>9. Changes to Terms</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            We may update these Terms from time to time. We will notify you of significant changes
            by posting a notice on the Service or sending you an email. Continued use of the Service
            after changes constitutes acceptance of the new Terms.
          </p>
        </section>

        <section style={{ marginBottom: '32px' }}>
          <h2 style={{ color: colors.cyan, fontSize: '16px' }}>10. Contact</h2>
          <p style={{ lineHeight: '1.7', color: colors.text }}>
            For questions about these Terms, please contact us at{' '}
            <a href="mailto:sky@veridian.run" style={{ color: colors.cyan }}>sky@veridian.run</a>.
          </p>
        </section>

        {/* VERIDIAN Ethics Notice */}
        <div style={{
          marginTop: '48px',
          padding: '24px',
          border: `1px solid ${colors.muted}`,
          textAlign: 'center',
        }}>
          <p style={{ color: colors.cyan, margin: '0 0 8px 0' }}>
            VERIDIAN TOOLS ETHICS COMMITMENT
          </p>
          <p style={{ color: colors.muted, margin: 0, fontSize: '13px', lineHeight: '1.6' }}>
            We believe technology should serve users, not exploit them. RegexGPT contains no dark patterns,
            no manipulative design, and no hidden fees. 15% of our revenue supports free emotional
            technology sanctuaries for those who need them most.
          </p>
        </div>
      </main>

      {/* Footer */}
      <footer style={{
        borderTop: `1px solid ${colors.muted}`,
        padding: '16px 24px',
        textAlign: 'center',
        color: colors.muted,
        fontSize: '12px',
      }}>
        (c) 2026 RegexGPT · A VERIDIAN TOOLS Product
      </footer>
    </div>
  )
}
